spring:
  application:
    name: SCW-PROJECT
  datasource:
    username: root
    password: administrator
    url: jdbc:mysql://localhost:3306/crowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
  redis:
    host: localhost
    port: 6379
    #password: 123456
  servlet: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true
 
server:
  port: 8000
  
swagger2: 
  enable: true
  
feign:
  hystrix:
    enabled: true 
    
    
oss: 
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIbmStluJokZHo
  accessKeySecret: IkJcFvF2v68UOt9xIUwrcRBnl0AHOU
  bucket: atcrowdfunding20190717
